### ISSUE TITLE
ItemBridge support for Display Items & Rewards

### ISSUE THREAD

**Issue by HSGamer** [Oribuin/EternalCrates#3]
Currently the plugin supports basic options for display items and rewards.
This can be extended to support for custom items (Quality Armory, items with BukkitDataValues, oraxen, etc) or user-defined in-game items (from its commands)

Link: https://www.spigotmc.org/resources/itembridge-save-items-and-use-them-wherever-you-want-including-other-plugins-best-w-customitems.77080/

One may use one setting (`itembridge`?) to retrieve the item for displaying, and one action (`[GIVE-ITEMBRIDGE]`?) to give the item to the player.

**Comment by Oribuin** [comment]
I will say, This does somewhat seem relatively unnecessary because you could just use the command "/itembridge give <player> <item> [amount]" to give a player item and the display items are purely visual so you could very likely just do any custom model data if needed.

**Comment by HSGamer** [comment]
I can just set 1 item for both display item and reward. If I want to change the item, I just need to change it in ItemBridge, instead of updating the display item and reward, which is somewhat annoying.

**Comment by HSGamer** [comment]
I want to set the item in-game, instead of hardcoding it in the config. I can just create a reward with the same display and given item, then set the item in-game with ItemBridge, then I can just set the percentage for that item.

**Comment by HSGamer** [comment]
It's hard to get anything right with the current approach.
If we support this ItemBridge, we have to load the display items and rewards passively, which means the crates will only be loaded after all other plugins are enabled, and the display items and rewards call the `getItem` method only when it's needed, not when the crate are loaded and active.
The current approach may get conflict with some plugins that are enabled after `EternalCrates` is enabled (Custom Enchants, Custom Items, etc).

**Comment by Oribuin** [comment]
oh boy look at those fast github reply speeds

anyway sorry to bother you after so long, but i'd just like to mention that ItemBridge support will be added along with a large variety of other plugins in v1.0.5 since i've been spending several hours on a plugin recode, not sure if you're still looking for this.

**Comment by HSGamer** [comment]
That's great if you do that. I'm still finding for an alternative for those crate plugins.

**Comment by Oribuin** [comment]
If you want a list of plugins that are supported, you can find it here 

https://github.com/Oribuin/EternalCrates/blob/plugin-rework/Plugin/src/main/java/xyz/oribuin/eternalcrates/hook/CustomItemPlugin.java
